Zaviermiller kkb 39 event card
hack4impact-utk/keep-knox-beautiful pull request #22
Opened 2021-03-01 07:02 UTC by zaviermiller

2021-03-02 17:31 UTC, kemalfidan approved these changes

2021-03-02 17:31 UTC, kemalfidan commented on src/components/EventCard/index.tsx
> +            background: `#97BBCB url("/${constants.org.images.defaultCard}") no-repeat center`,
Good stuff  👍

2021-03-02 17:31 UTC, kemalfidan commented on src/pages/index.tsx
> +                        <DDate />
You can remove the Dummy Date here. I just used that to get the exact format that MUI used for formatting the input date.

2021-03-02 17:31 UTC, kemalfidan commented on tst/components/EventCard.test.tsx
> +import { shallow } from "enzyme";
Really nice tests! I'll have to reference this for future UI components.

2021-03-03 03:44 UTC, kemalfidan requested changes

2021-03-03 03:44 UTC, kemalfidan commented on src/components/EventCard/index.tsx
> +            backgroundColor: "#87CD9B",
Can you replace this with colors from theme?

2021-03-03 03:44 UTC, kemalfidan commented on src/components/EventCard/index.tsx
> +            background: `#97BBCB url("/${constants.org.images.defaultCard}") no-repeat center`,
After revisiting this - could you replace this hex color as well? I think the blue in the colors is a placeholder. So can replace that blue and add a dark blue in the colors file. You can also make blue the secondary palette in `theme.ts` and use those colors here.

2021-03-03 03:46 UTC, rossketron approved these changes
Looks great! I'll definitely be referencing your tests when working on mine

2021-03-03 13:07 UTC, zaviermiller commented
@kemalfidan going to work today on fixing those changes, and I also noticed that I use inline styling a lot and I should probably use CSS classes

2021-03-09 01:06 UTC, kemalfidan approved these changes
Looks good! This is a core component of the site so good work :)

2021-03-09 02:23 UTC, merged