Andrewrutter/kkb 41 event signup frontend
hack4impact-utk/keep-knox-beautiful pull request #23
Opened 2021-03-02 06:33 UTC by andlrutt

This is the frontend component for event sign-ups. Collects name, email, and phone number, and requires that volunteers acknowledge the waiver. The waiver has not been linked, but it'll be easy enough to add a `to="/path"` to the Link element once that is established. Down the line, we'll need to add functionality to the sign-up button to check each field to make sure it has valid text, as currently the button currently only logs that it was pressed to the console. Also added a `lightGray` color to be used for input fields across the site. Below is what the component looks like.
![frontend](https://user-images.githubusercontent.com/71574118/109608045-3afb7180-7af7-11eb-9061-1e71cabf11cd.png)

2021-03-03 05:57 UTC, kemalfidan requested changes, later dismissed
I noticed a few things:
1. The component isn't really responsive. It looks nice on a large screen but when I make the screen size smaller, the display doesn't adjust to that screen. To fix this, can you add a media query to stack the signup form rather than put it side by side. I'll try to mock this up quickly on Figma.
2. Is it possible to get a `Volunteer` variable of the data in the form? There's different ways to set this up but I think [this](https://github.com/hack4impact-utk/mindversity-website/blob/develop/components/CreateJournalEntry/index.tsx) is probably a good reference.

2021-03-03 05:57 UTC, kemalfidan commented on src/components/EventForm/index.tsx
> +export default function EventsForm() {
Can you name this `EventForm` to be consistent with the filename? I actually like `EventSignUp` better.

2021-03-03 05:57 UTC, kemalfidan commented on src/components/EventForm/index.tsx
> +            borderColor: colors.green,
Can you use the primary color from `theme` here? Should be `theme.palette.primary.main`.

2021-03-03 05:57 UTC, kemalfidan commented on src/components/EventForm/index.tsx
> +            backgroundColor: colors.green,
`theme.palette.primary.main`

2021-03-03 05:57 UTC, kemalfidan commented on src/components/EventForm/index.tsx
> +            backgroundColor: colors.green,
Same as above

2021-03-08 15:05 UTC, kemalfidan reviewed
The changes look great! Thanks for handling that. Are you still using the waiver symbol image under public? If not do you mind removing that? I know Java has a mask formatted for formatting the input - [this](https://www.npmjs.com/package/react-input-mask) seems like it might be useful for what we're looking for. A simple (XXX)XXX-XXXX or XXX-XXX-XXXX is what we're looking for.

2021-03-08 15:05 UTC, kemalfidan commented on src/components/EventSignUp/index.tsx
> +                width: "371px",
Can you decrease the height here? I feel like it's a lot to scroll through when looking on mobile. A short header like on the Figma would look better I think. Feel free to let me know what you/others think!

2021-03-08 15:05 UTC, kemalfidan commented on src/components/EventSignUp/index.tsx
> +            phone: phoneNumber.current!.value,
phone number might be optional so I think this should be `phoneNumber.current?.value`

2021-03-08 16:09 UTC, andlrutt commented on src/components/EventSignUp/index.tsx
> +                width: "371px",
Ah, didn't catch that mockup on Figma, thanks!

2021-03-09 02:25 UTC, zaviermiller approved these changes

2021-03-09 03:06 UTC, rossketron approved these changes
Looks great!

2021-03-10 02:00 UTC, merged